"""add new column to 'embedding1536' table

Revision ID: 50fb81290a5d
Revises: f23549b30bda
Create Date: 2026-03-28 01:58:24.318930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50fb81290a5d'
down_revision: Union[str, Sequence[str], None] = 'f23549b30bda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding_1536', sa.Column('resume_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embedding_1536', 'resume_text')
    # ### end Alembic commands ###
